name: LightVote
main: com.gmail.zariust.LightVote.LightVote
version: 1.80t
authors:
  - xupwup
  - Xarqn
  - Tickleman

commands:
    lvt:
        description: Vote for day, night or sun.
        usage: /<command>
