name: LightVote
main: com.gmail.zariust.LightVote.LightVote
version: 1.9
authors:
  - xupwup
  - Xarqn
  - Tickleman

commands:
    lvt:
        description: Vote for day, night or sun.
        aliases: [vote, lightvote]
        usage: /<command>
