name: LightVote
main: com.gmail.zariust.LightVote.LightVote
version: 1.71t
authors:
  - xupwup
  - Xarqn
  - Tickleman

commands:
    lvt:
        description: Vote for day or night.
        usage: /<command>